package mapper;

import model.User;

import java.util.ArrayList;

public interface NewsuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NEWSUSER
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NEWSUSER
     *
     * @mbggenerated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NEWSUSER
     *
     * @mbggenerated
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NEWSUSER
     *
     * @mbggenerated
     */
    User selectByPrimaryKey(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NEWSUSER
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NEWSUSER
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(User record);
 /* 动态sql*/
    ArrayList<User> selectSelective(User rocord);
}
