package mapper;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import model.New;
import model.NewsExample;
import org.apache.ibatis.annotations.Param;

public interface NewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NEWS
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(BigDecimal newid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NEWS
     *
     * @mbggenerated
     */
    int insert(New record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NEWS
     *
     * @mbggenerated
     */
    int insertSelective(New record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NEWS
     *
     * @mbggenerated
     */
    List<New> selectByExample(NewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NEWS
     *
     * @mbggenerated
     */
    New selectByPrimaryKey(BigDecimal newid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NEWS
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(New record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NEWS
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(New record);

    /**
     *
     * @param rocord
     * @return
     */
    ArrayList<New> selectSelective(@Param("reocord") New rocord);



}